language: android


android:
  components:
    - tools
    - build-tools-28.0.3
    - extra-android-support
    - extra-google-m2repository
    - extra-android-2repository

licenses:
  -'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew clean ktlint test