language: android
env:
  global:
    - CODECOV_TOKEN = 18f04d95-4404-4b3b-b805-d69c4f9a21c9

android:
  components:
    - tools
    - build-tools-28.0.3
    - extra-android-support
    - extra-google-m2repository
    - extra-android-2repository

licenses:
  -'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"
  - pip install --user codecov


after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)

script:
  - ./gradlew clean test build jacocoTestReport assembleAndroidTest connectedCheck